### ISSUE TITLE
Question about closed-form solution

### ISSUE THREAD

**Issue by yanwuxingchen** [idstcv/SeCu#2]
Hello, I would like to ask how the optimization through closed-form solution mentioned in your paper is realized, I did not find it in the code you gave, thank you very much!

**Comment by qian-qi** [comment]
Thank you for your interest. Due to the better performance of SGD, we didn't include the closed-form solution in this repo. However, you can find a similar one in our previous work CoKe: https://github.com/idstcv/CoKe

**Comment by qian-qi** [comment]
I will close the issue and you can reopen it if you have any other questions.
